In [12]:
import pandas as pd

# Step 1: Load the CSV

In [13]:
df = pd.read_csv('..\\updated_lineup_vs_lineup\\lineup_vs_lineup_with_team_id.csv')

In [14]:
df = df.fillna(0)

In [15]:
df

,game_id,period,start_event,end_event,start_time,end_time,home_lineup,away_lineup,home_team_id,away_team_id,...,home_fouls,away_blocks,home_steals,away_turnovers,away_off_rebounds,away_fouls,away_ft_made,home_off_rebounds,home_ft_made,home_blocks
0,22301195,1,7,28,11:44,9:03,"('Brandon Ingram', 'CJ McCollum', 'Herbert Jon...","('Anthony Davis', 'Austin Reaves', ""D'Angelo R...",1610612740,1610612747,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,22301195,1,28,52,9:03,7:15,"('Brandon Ingram', 'CJ McCollum', 'Herbert Jon...","('Anthony Davis', 'Austin Reaves', ""D'Angelo R...",1610612740,1610612747,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,22301195,1,52,64,7:15,5:38,"('CJ McCollum', 'Herbert Jones', 'Larry Nance ...","('Anthony Davis', 'Austin Reaves', ""D'Angelo R...",1610612740,1610612747,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,22301195,1,64,90,5:38,3:43,"('Herbert Jones', 'Jose Alvarado', 'Larry Nanc...","('Anthony Davis', 'Austin Reaves', 'LeBron Jam...",1610612740,1610612747,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
4,22301195,1,90,109,3:43,2:05,"('Brandon Ingram', 'Herbert Jones', 'Jose Alva...","('Anthony Davis', ""D'Angelo Russell"", 'Rui Hac...",1610612740,1610612747,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81084,22300062,4,665,688,4:41,3:21,"('Gary Payton II', 'Jonathan Kuminga', 'Kevon ...","('Devin Booker', 'Grayson Allen', 'Josh Okogie...",1610612744,1610612756,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
81085,22300062,4,688,709,3:21,1:32,"('Chris Paul', 'Jonathan Kuminga', 'Kevon Loon...","('Devin Booker', 'Grayson Allen', 'Josh Okogie...",1610612744,1610612756,...,0.0,0.0,1.0,3.0,0.0,1.0,0.0,1.0,0.0,0.0
81086,22300062,4,709,726,1:32,0:30,"('Chris Paul', 'Jonathan Kuminga', 'Kevon Loon...","('Devin Booker', 'Eric Gordon', 'Josh Okogie',...",1610612744,1610612756,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0
81087,22300062,4,726,729,0:30,0:10,"('Chris Paul', 'Gary Payton II', 'Jonathan Kum...","('Devin Booker', 'Eric Gordon', 'Josh Okogie',...",1610612744,1610612756,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
81088,22300062,4,729,742,0:10,0:00,"('Chris Paul', 'Kevon Looney', 'Klay Thompson'...","('Devin Booker', 'Eric Gordon', 'Grayson Allen...",1610612744,1610612756,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

# Step 2: Define the formula for lineup_score

In [16]:
# Time conversion helper (from MM:SS to total seconds)
def time_to_seconds(t):
    minutes, seconds = map(int, str(t).split(":"))
    return minutes * 60 + seconds

# Convert start_time and end_time to seconds
df['start_sec'] = df['start_time'].apply(time_to_seconds)
df['end_sec'] = df['end_time'].apply(time_to_seconds)
df['duration'] = df['start_sec'] - df['end_sec']  # time moving backward (start_time > end_time)

In [17]:
df.head()

,game_id,period,start_event,end_event,start_time,end_time,home_lineup,away_lineup,home_team_id,away_team_id,...,away_turnovers,away_off_rebounds,away_fouls,away_ft_made,home_off_rebounds,home_ft_made,home_blocks,start_sec,end_sec,duration
0,22301195,1,7,28,11:44,9:03,"('Brandon Ingram', 'CJ McCollum', 'Herbert Jon...","('Anthony Davis', 'Austin Reaves', ""D'Angelo R...",1610612740,1610612747,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,704,543,161
1,22301195,1,28,52,9:03,7:15,"('Brandon Ingram', 'CJ McCollum', 'Herbert Jon...","('Anthony Davis', 'Austin Reaves', ""D'Angelo R...",1610612740,1610612747,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,543,435,108
2,22301195,1,52,64,7:15,5:38,"('CJ McCollum', 'Herbert Jones', 'Larry Nance ...","('Anthony Davis', 'Austin Reaves', ""D'Angelo R...",1610612740,1610612747,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,435,338,97
3,22301195,1,64,90,5:38,3:43,"('Herbert Jones', 'Jose Alvarado', 'Larry Nanc...","('Anthony Davis', 'Austin Reaves', 'LeBron Jam...",1610612740,1610612747,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,338,223,115
4,22301195,1,90,109,3:43,2:05,"('Brandon Ingram', 'Herbert Jones', 'Jose Alva...","('Anthony Davis', ""D'Angelo Russell"", 'Rui Hac...",1610612740,1610612747,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,223,125,98

In [18]:
df['home_score'] = (
    1.0 * df['home_points'] +
    0.7 * df['home_assists'] +
    1.0 * df['home_3pt_made'] +
    1.0 * df['home_2pt_made'] +
    0.5 * df['home_ft_made'] +
    0.7 * df['home_steals'] +
    0.5 * df['home_blocks'] +
    0.3 * df['home_def_rebounds'] +
    0.3 * df['home_off_rebounds'] +
    (-1.0) * df['home_turnovers'] +
    (-0.3) * df['home_fouls']
)

df['away_score'] = (
    1.0 * df['away_points'] +
    0.7 * df['away_assists'] +
    1.0 * df['away_3pt_made'] +
    1.0 * df['away_2pt_made'] +
    0.5 * df['away_ft_made'] +
    0.7 * df['away_steals'] +
    0.5 * df['away_blocks'] +
    0.3 * df['away_def_rebounds'] +
    0.3 * df['away_off_rebounds'] +
    (-1.0) * df['away_turnovers'] +
    (-0.3) * df['away_fouls']
)

In [19]:
df['normalized_home_score'] = df['home_score'] / df['duration']
df['normalized_away_score'] = df['away_score'] / df['duration']
df['net_score'] = df['normalized_home_score'] - df['normalized_away_score']

In [20]:
df

,game_id,period,start_event,end_event,start_time,end_time,home_lineup,away_lineup,home_team_id,away_team_id,...,home_ft_made,home_blocks,start_sec,end_sec,duration,home_score,away_score,normalized_home_score,normalized_away_score,net_score
0,22301195,1,7,28,11:44,9:03,"('Brandon Ingram', 'CJ McCollum', 'Herbert Jon...","('Anthony Davis', 'Austin Reaves', ""D'Angelo R...",1610612740,1610612747,...,0.0,0.0,704,543,161,5.7,20.5,0.035404,0.127329,-0.091925
1,22301195,1,28,52,9:03,7:15,"('Brandon Ingram', 'CJ McCollum', 'Herbert Jon...","('Anthony Davis', 'Austin Reaves', ""D'Angelo R...",1610612740,1610612747,...,0.0,0.0,543,435,108,4.0,9.2,0.037037,0.085185,-0.048148
2,22301195,1,52,64,7:15,5:38,"('CJ McCollum', 'Herbert Jones', 'Larry Nance ...","('Anthony Davis', 'Austin Reaves', ""D'Angelo R...",1610612740,1610612747,...,0.0,0.0,435,338,97,3.7,3.7,0.038144,0.038144,0.000000
3,22301195,1,64,90,5:38,3:43,"('Herbert Jones', 'Jose Alvarado', 'Larry Nanc...","('Anthony Davis', 'Austin Reaves', 'LeBron Jam...",1610612740,1610612747,...,0.0,0.0,338,223,115,8.7,7.3,0.075652,0.063478,0.012174
4,22301195,1,90,109,3:43,2:05,"('Brandon Ingram', 'Herbert Jones', 'Jose Alva...","('Anthony Davis', ""D'Angelo Russell"", 'Rui Hac...",1610612740,1610612747,...,0.0,0.0,223,125,98,4.3,5.0,0.043878,0.051020,-0.007143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81084,22300062,4,665,688,4:41,3:21,"('Gary Payton II', 'Jonathan Kuminga', 'Kevon ...","('Devin Booker', 'Grayson Allen', 'Josh Okogie...",1610612744,1610612756,...,1.0,0.0,281,201,80,1.1,6.5,0.013750,0.081250,-0.067500
81085,22300062,4,688,709,3:21,1:32,"('Chris Paul', 'Jonathan Kuminga', 'Kevon Loon...","('Devin Booker', 'Grayson Allen', 'Josh Okogie...",1610612744,1610612756,...,0.0,0.0,201,92,109,3.0,-3.0,0.027523,-0.027523,0.055046
81086,22300062,4,709,726,1:32,0:30,"('Chris Paul', 'Jonathan Kuminga', 'Kevon Loon...","('Devin Booker', 'Eric Gordon', 'Josh Okogie',...",1610612744,1610612756,...,2.0,0.0,92,30,62,7.7,9.4,0.124194,0.151613,-0.027419
81087,22300062,4,726,729,0:30,0:10,"('Chris Paul', 'Gary Payton II', 'Jonathan Kum...","('Devin Booker', 'Eric Gordon', 'Josh Okogie',...",1610612744,1610612756,...,0.0,0.0,30,10,20,0.0,0.0,0.000000,0.000000,0.000000
81088,22300062,4,729,742,0:10,0:00,"('Chris Paul', 'Kevon Looney', 'Klay Thompson'...","('Devin Booker', 'Eric Gordon', 'Grayson Allen...",1610612744,1610612756,...,0.0,0.0,10,0,10,0.3,4.0,0.030000,0.400000,-0.370000

# Step 3: Save to a new CSV

In [21]:
df.to_csv('lineup_score_with_team_id.csv', index=False)

print("✅ New file saved as 'lineup_score_with_team_id.csv'")

✅ New file saved as 'lineup_score_with_team_id.csv'

In [22]:
df.head()

,game_id,period,start_event,end_event,start_time,end_time,home_lineup,away_lineup,home_team_id,away_team_id,...,home_ft_made,home_blocks,start_sec,end_sec,duration,home_score,away_score,normalized_home_score,normalized_away_score,net_score
0,22301195,1,7,28,11:44,9:03,"('Brandon Ingram', 'CJ McCollum', 'Herbert Jon...","('Anthony Davis', 'Austin Reaves', ""D'Angelo R...",1610612740,1610612747,...,0.0,0.0,704,543,161,5.7,20.5,0.035404,0.127329,-0.091925
1,22301195,1,28,52,9:03,7:15,"('Brandon Ingram', 'CJ McCollum', 'Herbert Jon...","('Anthony Davis', 'Austin Reaves', ""D'Angelo R...",1610612740,1610612747,...,0.0,0.0,543,435,108,4.0,9.2,0.037037,0.085185,-0.048148
2,22301195,1,52,64,7:15,5:38,"('CJ McCollum', 'Herbert Jones', 'Larry Nance ...","('Anthony Davis', 'Austin Reaves', ""D'Angelo R...",1610612740,1610612747,...,0.0,0.0,435,338,97,3.7,3.7,0.038144,0.038144,0.000000
3,22301195,1,64,90,5:38,3:43,"('Herbert Jones', 'Jose Alvarado', 'Larry Nanc...","('Anthony Davis', 'Austin Reaves', 'LeBron Jam...",1610612740,1610612747,...,0.0,0.0,338,223,115,8.7,7.3,0.075652,0.063478,0.012174
4,22301195,1,90,109,3:43,2:05,"('Brandon Ingram', 'Herbert Jones', 'Jose Alva...","('Anthony Davis', ""D'Angelo Russell"", 'Rui Hac...",1610612740,1610612747,...,0.0,0.0,223,125,98,4.3,5.0,0.043878,0.051020,-0.007143