In [2]:
import pandas as pd

# Step 1: Load the CSV

In [20]:
df = pd.read_csv('..\\updated_lineup_vs_lineup\\PRE_updated_lineup_vs_lineup.csv')

In [27]:
df = df.fillna(0)

In [28]:
df

,game_id,period,start_event,end_event,start_time,end_time,home_lineup,away_lineup,home_blocks,home_2pt_made,...,away_assists,away_steals,away_blocks,away_ft_made,away_fouls,home_steals,home_3pt_made,start_sec,end_sec,duration
0,12300069,1,7,59,11:43,7:27,"('Dennis Schroder', 'Jakob Poeltl', 'OG Anunob...","('Bilal Coulibaly', 'Daniel Gafford', 'Deni Av...",0.0,2.0,...,4.0,0.0,1.0,1.0,1.0,1.0,0.0,703,447,256
1,12300069,1,59,92,7:27,4:47,"('Dennis Schroder', 'OG Anunoby', 'Pascal Siak...","('Bilal Coulibaly', 'Daniel Gafford', 'Deni Av...",1.0,2.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,447,287,160
2,12300069,1,92,122,4:47,3:06,"('Dennis Schroder', 'Gradey Dick', 'Jalen McDa...","('Bilal Coulibaly', 'Corey Kispert', 'Delon Wr...",2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,287,186,101
3,12300069,1,122,136,3:06,2:20,"('Gradey Dick', 'Jalen McDaniels', 'Malachi Fl...","('Corey Kispert', 'Danilo Gallinari', 'Delon W...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,186,140,46
4,12300069,1,136,143,2:20,1:54,"('Gradey Dick', 'Jalen McDaniels', 'Malachi Fl...","('Corey Kispert', 'Danilo Gallinari', 'Delon W...",0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,140,114,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2965,2012300001,4,657,659,4:27,4:27,"('Babacar Sané', 'London Johnson', 'Matas Buze...","('David Okwera', 'Hyrum Harris', 'Jordan Usher...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,267,267,0
2966,2012300001,4,659,662,4:27,4:12,"('Babacar Sané', 'London Johnson', 'Matas Buze...","('Bryce Cotton', 'David Okwera', 'Hyrum Harris...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,267,252,15
2967,2012300001,4,662,681,4:12,3:28,"('Babacar Sané', 'London Johnson', 'Matas Buze...","('David Okwera', 'Hyrum Harris', 'Jordan Usher...",0.0,1.0,...,1.0,0.0,0.0,2.0,0.0,0.0,0.0,252,208,44
2968,2012300001,4,681,700,3:28,1:24,"('Babacar Sané', 'Izan Almansa', 'London Johns...","('David Okwera', 'Hyrum Harris', 'Jordan Usher...",0.0,1.0,...,4.0,2.0,0.0,0.0,1.0,1.0,1.0,208,84,124
2969,2012300001,4,700,726,1:24,0:00,"('Babacar Sané', 'Izan Almansa', 'London Johns...","('David Okwera', 'Dontae Russo-Nance', 'Hyrum ...",0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,84,0,84

# Step 2: Define the formula for lineup_score

In [29]:
# Time conversion helper (from MM:SS to total seconds)
def time_to_seconds(t):
    minutes, seconds = map(int, str(t).split(":"))
    return minutes * 60 + seconds

# Convert start_time and end_time to seconds
df['start_sec'] = df['start_time'].apply(time_to_seconds)
df['end_sec'] = df['end_time'].apply(time_to_seconds)
df['duration'] = df['start_sec'] - df['end_sec']  # time moving backward (start_time > end_time)

In [30]:
df.head()

,game_id,period,start_event,end_event,start_time,end_time,home_lineup,away_lineup,home_blocks,home_2pt_made,...,away_assists,away_steals,away_blocks,away_ft_made,away_fouls,home_steals,home_3pt_made,start_sec,end_sec,duration
0,12300069,1,7,59,11:43,7:27,"('Dennis Schroder', 'Jakob Poeltl', 'OG Anunob...","('Bilal Coulibaly', 'Daniel Gafford', 'Deni Av...",0.0,2.0,...,4.0,0.0,1.0,1.0,1.0,1.0,0.0,703,447,256
1,12300069,1,59,92,7:27,4:47,"('Dennis Schroder', 'OG Anunoby', 'Pascal Siak...","('Bilal Coulibaly', 'Daniel Gafford', 'Deni Av...",1.0,2.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,447,287,160
2,12300069,1,92,122,4:47,3:06,"('Dennis Schroder', 'Gradey Dick', 'Jalen McDa...","('Bilal Coulibaly', 'Corey Kispert', 'Delon Wr...",2.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,287,186,101
3,12300069,1,122,136,3:06,2:20,"('Gradey Dick', 'Jalen McDaniels', 'Malachi Fl...","('Corey Kispert', 'Danilo Gallinari', 'Delon W...",0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,186,140,46
4,12300069,1,136,143,2:20,1:54,"('Gradey Dick', 'Jalen McDaniels', 'Malachi Fl...","('Corey Kispert', 'Danilo Gallinari', 'Delon W...",0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,140,114,26

In [31]:
df['home_score'] = (
    1.0 * df['home_points'] +
    0.7 * df['home_assists'] +
    1.0 * df['home_3pt_made'] +
    1.0 * df['home_2pt_made'] +
    0.5 * df['home_ft_made'] +
    0.7 * df['home_steals'] +
    0.5 * df['home_blocks'] +
    0.3 * df['home_def_rebounds'] +
    0.3 * df['home_off_rebounds'] +
    (-1.0) * df['home_turnovers'] +
    (-0.3) * df['home_fouls']
)

df['away_score'] = (
    1.0 * df['away_points'] +
    0.7 * df['away_assists'] +
    1.0 * df['away_3pt_made'] +
    1.0 * df['away_2pt_made'] +
    0.5 * df['away_ft_made'] +
    0.7 * df['away_steals'] +
    0.5 * df['away_blocks'] +
    0.3 * df['away_def_rebounds'] +
    0.3 * df['away_off_rebounds'] +
    (-1.0) * df['away_turnovers'] +
    (-0.3) * df['away_fouls']
)

In [32]:
df['normalized_home_score'] = df['home_score'] / df['duration']
df['normalized_away_score'] = df['away_score'] / df['duration']
df['net_score'] = df['normalized_home_score'] - df['normalized_away_score']

In [33]:
df

,game_id,period,start_event,end_event,start_time,end_time,home_lineup,away_lineup,home_blocks,home_2pt_made,...,home_steals,home_3pt_made,start_sec,end_sec,duration,home_score,away_score,normalized_home_score,normalized_away_score,net_score
0,12300069,1,7,59,11:43,7:27,"('Dennis Schroder', 'Jakob Poeltl', 'OG Anunob...","('Bilal Coulibaly', 'Daniel Gafford', 'Deni Av...",0.0,2.0,...,1.0,0.0,703,447,256,8.9,21.0,0.034766,0.082031,-0.047266
1,12300069,1,59,92,7:27,4:47,"('Dennis Schroder', 'OG Anunoby', 'Pascal Siak...","('Bilal Coulibaly', 'Daniel Gafford', 'Deni Av...",1.0,2.0,...,1.0,1.0,447,287,160,13.5,6.9,0.084375,0.043125,0.041250
2,12300069,1,92,122,4:47,3:06,"('Dennis Schroder', 'Gradey Dick', 'Jalen McDa...","('Bilal Coulibaly', 'Corey Kispert', 'Delon Wr...",2.0,3.0,...,0.0,0.0,287,186,101,11.6,0.0,0.114851,0.000000,0.114851
3,12300069,1,122,136,3:06,2:20,"('Gradey Dick', 'Jalen McDaniels', 'Malachi Fl...","('Corey Kispert', 'Danilo Gallinari', 'Delon W...",0.0,0.0,...,0.0,1.0,186,140,46,5.3,-1.0,0.115217,-0.021739,0.136957
4,12300069,1,136,143,2:20,1:54,"('Gradey Dick', 'Jalen McDaniels', 'Malachi Fl...","('Corey Kispert', 'Danilo Gallinari', 'Delon W...",0.0,0.0,...,0.0,1.0,140,114,26,4.7,3.7,0.180769,0.142308,0.038462
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2965,2012300001,4,657,659,4:27,4:27,"('Babacar Sané', 'London Johnson', 'Matas Buze...","('David Okwera', 'Hyrum Harris', 'Jordan Usher...",0.0,0.0,...,0.0,0.0,267,267,0,0.0,0.0,NaN,NaN,NaN
2966,2012300001,4,659,662,4:27,4:12,"('Babacar Sané', 'London Johnson', 'Matas Buze...","('Bryce Cotton', 'David Okwera', 'Hyrum Harris...",0.0,0.0,...,0.0,0.0,267,252,15,0.0,0.0,0.000000,0.000000,0.000000
2967,2012300001,4,662,681,4:12,3:28,"('Babacar Sané', 'London Johnson', 'Matas Buze...","('David Okwera', 'Hyrum Harris', 'Jordan Usher...",0.0,1.0,...,0.0,0.0,252,208,44,2.7,8.0,0.061364,0.181818,-0.120455
2968,2012300001,4,681,700,3:28,1:24,"('Babacar Sané', 'Izan Almansa', 'London Johns...","('David Okwera', 'Hyrum Harris', 'Jordan Usher...",0.0,1.0,...,1.0,1.0,208,84,124,5.4,17.2,0.043548,0.138710,-0.095161
2969,2012300001,4,700,726,1:24,0:00,"('Babacar Sané', 'Izan Almansa', 'London Johns...","('David Okwera', 'Dontae Russo-Nance', 'Hyrum ...",0.0,0.0,...,0.0,0.0,84,0,84,0.8,6.7,0.009524,0.079762,-0.070238

# Step 3: Save to a new CSV

In [34]:
df.to_csv('nba_with_lineup_score.csv', index=False)

print("✅ New file saved as 'nba_with_lineup_score.csv'")

✅ New file saved as 'nba_with_lineup_score.csv'

In [19]:
df.head()

,game_id,period,start_event,end_event,start_time,end_time,home_lineup,away_lineup,home_blocks,home_2pt_made,...,home_steals,home_3pt_made,start_sec,end_sec,duration,home_score,away_score,normalized_home_score,normalized_away_score,net_score
0,12300069,1,7,59,11:43,7:27,"('Dennis Schroder', 'Jakob Poeltl', 'OG Anunob...","('Bilal Coulibaly', 'Daniel Gafford', 'Deni Av...",NaN,2.0,...,1.0,NaN,703,447,256,NaN,NaN,NaN,NaN,NaN
1,12300069,1,59,92,7:27,4:47,"('Dennis Schroder', 'OG Anunoby', 'Pascal Siak...","('Bilal Coulibaly', 'Daniel Gafford', 'Deni Av...",1.0,2.0,...,1.0,1.0,447,287,160,NaN,NaN,NaN,NaN,NaN
2,12300069,1,92,122,4:47,3:06,"('Dennis Schroder', 'Gradey Dick', 'Jalen McDa...","('Bilal Coulibaly', 'Corey Kispert', 'Delon Wr...",2.0,3.0,...,NaN,NaN,287,186,101,NaN,NaN,NaN,NaN,NaN
3,12300069,1,122,136,3:06,2:20,"('Gradey Dick', 'Jalen McDaniels', 'Malachi Fl...","('Corey Kispert', 'Danilo Gallinari', 'Delon W...",NaN,NaN,...,NaN,1.0,186,140,46,NaN,NaN,NaN,NaN,NaN
4,12300069,1,136,143,2:20,1:54,"('Gradey Dick', 'Jalen McDaniels', 'Malachi Fl...","('Corey Kispert', 'Danilo Gallinari', 'Delon W...",NaN,NaN,...,NaN,1.0,140,114,26,NaN,NaN,NaN,NaN,NaN